/*Package gate*/
/*Code generated by gen.sh. DO NOT EDIT.*/
package gate

const RegisterReqCMD uint32 = 0x1001 // 注册请求 user->gate
const RegisterResCMD uint32 = 0x1002 // 注册响应 gate->user
const LogoutReqCMD uint32 = 0x1003   // 注销请求 user->gate
const LogoutResCMD uint32 = 0x1004   // 注销响应 gate->user
