/*Code generated by gen.sh. DO NOT EDIT.*/
package gate

const RegisterReq_CMD uint32 = 0x1001 // 注册请求 user->gate
const RegisterRes_CMD uint32 = 0x1002 // 注册响应 gate->user
const LogoutReq_CMD uint32 = 0x1003   // 注销请求 user->gate
const LogoutRes_CMD uint32 = 0x1004   // 注销响应 gate->user
