// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: gate_server.proto

package gate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	proto "social/pkg/proto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	BidirectionalBinaryData(ctx context.Context, opts ...grpc.CallOption) (Service_BidirectionalBinaryDataClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) BidirectionalBinaryData(ctx context.Context, opts ...grpc.CallOption) (Service_BidirectionalBinaryDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/Service/BidirectionalBinaryData", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceBidirectionalBinaryDataClient{stream}
	return x, nil
}

type Service_BidirectionalBinaryDataClient interface {
	Send(*proto.BinaryData) error
	Recv() (*proto.BinaryData, error)
	grpc.ClientStream
}

type serviceBidirectionalBinaryDataClient struct {
	grpc.ClientStream
}

func (x *serviceBidirectionalBinaryDataClient) Send(m *proto.BinaryData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceBidirectionalBinaryDataClient) Recv() (*proto.BinaryData, error) {
	m := new(proto.BinaryData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	BidirectionalBinaryData(Service_BidirectionalBinaryDataServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) BidirectionalBinaryData(Service_BidirectionalBinaryDataServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalBinaryData not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_BidirectionalBinaryData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).BidirectionalBinaryData(&serviceBidirectionalBinaryDataServer{stream})
}

type Service_BidirectionalBinaryDataServer interface {
	Send(*proto.BinaryData) error
	Recv() (*proto.BinaryData, error)
	grpc.ServerStream
}

type serviceBidirectionalBinaryDataServer struct {
	grpc.ServerStream
}

func (x *serviceBidirectionalBinaryDataServer) Send(m *proto.BinaryData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceBidirectionalBinaryDataServer) Recv() (*proto.BinaryData, error) {
	m := new(proto.BinaryData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service",
	HandlerType: (*ServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalBinaryData",
			Handler:       _Service_BidirectionalBinaryData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gate_server.proto",
}
