/*Code generated by gen.sh. DO NOT EDIT.*/
package error_code

import xrerror "social/pkg/lib/error"

var (
	EC_SUCCESS              = &xrerror.Error{Code: 0x0000, Name: "EC_SUCCESS", Desc: "成功"}
	EC_ACCOUNT_NON_EXISTENT = &xrerror.Error{Code: 0x1001, Name: "EC_ACCOUNT_NON_EXISTENT", Desc: "账号不存在"}
)
