/*Code generated by gen.sh. DO NOT EDIT.*/
package error_code

import xrerror "social/pkg/lib/error"

var (
	EC_Succe              = &xrerror.Error{Code: 0x0000, Name: "EC_Succe", Desc: "成功"}
	EC_AccountNonexitence = &xrerror.Error{Code: 0x1001, Name: "EC_AccountNonexitence", Desc: "账号不存在"}
)
