/*Package ec*/
/*Code generated by gen.sh. DO NOT EDIT.*/
package ec

import liberror "social/lib/error"

var (
	Success             = liberror.CreateError(0x0000, "Success", "成功")
	AccountNonexistence = liberror.CreateError(0x1001, "AccountNonexistence", "账号不存在")
)
